In [1]:
import pandas as pd

In [21]:
import pandas as pd
info = {
   "Name": ["Rahul","Harshita","Shradha"],
   "CGPA": [9.3,7.5,8.6]
}
df = pd.DataFrame(info) # pd.Dataframe is an important datastructure for making table of content
print(df)

       Name  CGPA
0     Rahul   9.3
1  Harshita   7.5
2   Shradha   8.6

In [23]:
df

       Name  CGPA
0     Rahul   9.3
1  Harshita   7.5
2   Shradha   8.6

In [15]:
s = pd.Series([1,2,3,4,5]) #A Series is a one-dimensional labeled array in Pandas
print(s,type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'>

In [ ]:
S = pd.Series([22,23,25,26], index = ["Adam","Sabrina","Ana","Charlie"])# Labeled is a named Index
print(S)

print(S["Adam"])
print(S.index)
'''
 * Series(Prooerties)
 1. Homogenous = same type of data are store only
 2. Vectorized Opertions = provide lable automatically
 3. Mutuble values, immutable size = Can not change the size but can replace the values

'''

Adam       22
Sabrina    23
Ana        25
Charlie    26
dtype: int64
22
Index(['Adam', 'Sabrina', 'Ana', 'Charlie'], dtype='object')

In [ ]:
# csv data
df = pd.read_csv("employee_data1.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

<bound method NDFrame.head of    ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000>

In [36]:
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [43]:
df.tail()
# df.tail(2)

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [50]:
df.sample()
df.info()
df.shape
df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [52]:
# AQI Data set
df = pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [ ]:
df.describe()
'''
Pandas Selecting Data
1. Select Columns 
2. Select Rows(Lable & Index based) - loc& iloc
3. Select Rows & Columns
4. Select single scalar value- at & iat
'''

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [83]:
df["city"]
df[["city","aqi"]]
df.loc[0]
df.loc[0:2] # ending index is inclusive

df.iloc[0]
df.iloc[0:2] # ending index is exclusive

df.iloc[0:3, 1:6]

df.at[0,"city"]
df.iat[0,2]

'New York'

In [ ]:
# Filtering of Data
df[ (df["aqi"]> 100) & (df["temperature"]>30)]
df[ (df["aqi"]> 100) & (df["temperature"]<30)]
df[(df["aqi"]>100) & (df["temperature"]>30)] 

aqi_data = df[(df["aqi"] > 100)&(df["temperature"]>30)] [["city","aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

# Query

city    New York
aqi          155
Name: 6, dtype: object